apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo
    namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: prime-site
        image: asia.gcr.io/common-kub/prime-app:v1
        ports:
        - containerPort: 8080

